# Generated by Django 5.1.4 on 2026-07-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг (URL)')),
                ('title', models.CharField(max_length=200, verbose_name='Название (внутреннее)')),
                ('meta_title', models.CharField(blank=True, max_length=300, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='SEO keywords')),
                ('og_title', models.CharField(blank=True, max_length=300, verbose_name='OG title')),
                ('og_description', models.TextField(blank=True, verbose_name='OG description')),
                ('og_image', models.ImageField(blank=True, upload_to='pages/', verbose_name='OG image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (916) 992-22-24', max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@ssu-138.ru', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='г. Москва', max_length=255, verbose_name='Адрес (короткий)')),
                ('inn', models.CharField(blank=True, default='9111027572', max_length=20, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, default='1219100000932', max_length=20, verbose_name='ОГРН')),
                ('legal_name', models.CharField(blank=True, default='ООО "ССУ 138"', max_length=255, verbose_name='Юр. название')),
                ('address_legal', models.CharField(blank=True, default='299053, г. Севастополь, ул. Отрадная, д. 15/1', max_length=255, verbose_name='Юридический адрес')),
                ('site_url', models.URLField(default='https://ssu-138.ru', verbose_name='URL сайта')),
                ('og_image', models.ImageField(blank=True, upload_to='site/', verbose_name='OG-картинка (для соцсетей)')),
                ('map_embed_url', models.URLField(blank=True, default='https://yandex.ru/map-widget/v1/?ll=33.485610%2C44.581079&z=17&pt=33.485610%2C44.581079%2Cpm2rdl&l=map&lang=ru_RU', max_length=1000, verbose_name='Ссылка на встраиваемую карту')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram включён')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Telegram bot token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat id')),
                ('telegram_thread_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram thread id')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('block_type', models.CharField(choices=[('hero', 'Hero (главный баннер)'), ('service_hero', 'Hero страницы услуги'), ('cards', 'Карточки услуг'), ('features', 'Фичи (нумерованные)'), ('projects', 'Проекты (объекты)'), ('stats', 'Статистика (счётчики)'), ('testimonial', 'Доверие / отзыв'), ('stages', 'Этапы'), ('contacts', 'Контакты + форма'), ('cta', 'Призыв к действию'), ('custom_html', 'Произвольный HTML')], default='custom_html', max_length=32, verbose_name='Тип блока')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('eyebrow', models.CharField(blank=True, max_length=200, verbose_name='Надзаголовок (mono)')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст / HTML')),
                ('image', models.ImageField(blank=True, upload_to='sections/', verbose_name='Картинка')),
                ('anchor', models.SlugField(blank=True, max_length=60, verbose_name='Якорь (id)')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Доп. настройки')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='Номер / значение')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='items/', verbose_name='Картинка')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Тег / метка')),
                ('link_text', models.CharField(blank=True, max_length=120, verbose_name='Текст ссылки')),
                ('link_url', models.CharField(blank=True, max_length=300, verbose_name='URL ссылки')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Элемент секции',
                'verbose_name_plural': 'Элементы секции',
                'ordering': ['order', 'id'],
            },
        ),
    ]
