# Generated by Django 5.1.4 on 2026-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_news_mirnoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero (главный баннер)'), ('service_hero', 'Hero страницы услуги'), ('cards', 'Карточки услуг'), ('features', 'Фичи (нумерованные)'), ('projects', 'Проекты (объекты)'), ('stats', 'Статистика (счётчики)'), ('testimonial', 'Доверие / отзыв'), ('stages', 'Этапы'), ('contacts', 'Контакты + форма'), ('cta', 'Призыв к действию'), ('news', 'Новость (статья + галерея)'), ('custom_html', 'Произвольный HTML')], default='custom_html', max_length=32, verbose_name='Тип блока'),
        ),
    ]
